title:
  en: Orbits Simulator
  es: Simulador de Órbitas
finished: finished
descriptionShort:
  en: The Three-Body Problem, a good Netflix series, shows what can happen in the universe when physics are involved with large objects (planets and stars). Here, I simulate the interaction of some objects using simple Newton's equations implemented in C++. We can enable collisions and make the objects behave like bouncing balls. Super fun.
  es: El problema de los tres cuerpos, una buena serie de Netflix, muestra lo que puede suceder en el universo cuando la física interviene con objetos grandes (planetas y estrellas). Aquí, simulo la interacción de algunos objetos utilizando las ecuaciones de Newton implementadas en C++. Podemos habilitar colisiones y hacer que los objetos se comporten como pelotas que rebotan. Súper divertido.
descriptionLong:
  en: |
    The Three-Body Problem, a good Netflix series, shows what can happen in the universe when physics are involved with large objects (planets and stars). Here, I simulate the interaction of some objects using simple Newton's equations implemented in C++. We can enable collisions and make the objects behave like bouncing balls. Super fun.
  es: |
    El problema de los tres cuerpos, una buena serie de Netflix, muestra lo que puede suceder en el universo cuando la física interviene con objetos grandes (planetas y estrellas). Aquí, simulo la interacción de algunos objetos utilizando las ecuaciones de Newton implementadas en C++. Podemos habilitar colisiones y hacer que los objetos se comporten como pelotas que rebotan. Súper divertido.
technologies: [c++]
tags: [personal]
logo: readme_images/Orbits (1)_169.webp
gif: readme_images/Orbits.gif
screenShoots:
  - readme_images/Orbits (1)_169.webp
  - readme_images/Orbits (2)_169.webp
  - readme_images/Orbits (3)_169.webp
  - readme_images/Orbits (4)_169.webp
  - readme_images/Orbits (5)_169.webp
  - readme_images/Orbits (6)_169.webp
  - readme_images/Orbits (7)_169.webp
  - readme_images/Orbits (8)_169.webp
youtube: UPl4bBSgKtM
keywords:
  en: [orbital mechanics, N-body simulation, three body problem, Newton gravity, planetary motion, celestial mechanics, bouncing collision, physics sandbox, space simulation, gravitational pull]
  es: [mecánica orbital, simulación N-cuerpos, problema de los tres cuerpos, gravedad de Newton, movimiento planetario, mecánica celeste, colisión elástica, sandbox físico, simulación espacial, atracción gravitatoria]
date:
  en: Feb 2025
  es: Feb 2025
slug: Orbits-Simulator
relevancy: 38
featured: false
